### ISSUE TITLE
nanopore_pipeline: error in compressing of final racon_polish

### ISSUE THREAD

**Issue by givdieri** [ZielsLab/ssUMI#2]
ssumi_std.sh produced an error for the test data at line 222:
>#Tidy up
>tar -czvf ${CON_DIR2}/mapping.tar.gz >${CON_DIR2}/umi*bins --remove-files

error in log-file:
>**tar: ssUMI_test/raconx3_medakax2_raconx1/umi*bins: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
ssUMI_test/umi_binning/read_binning/bins/
ssUMI_test/umi_binning/read_binning/bins/1/
ssUMI_test/umi_binning/read_binning/bins/1/umi2bins.fastq
ssUMI_test/umi_binning/read_binning/bins/1/umi3bins.fastq
ssUMI_test/umi_binning/read_binning/bins/1/umi4bins.fastq
ssUMI_test/umi_binning/read_binning/bins/1/umi1bins.fastq**

It is remedied by adjusting the directory to:
>#Tidy up
>tar -czvf ${CON_DIR2}/mapping.tar.gz >${CON_DIR2}/mapping/umi*bins --remove-files
>rmdir ${CON_DIR2}/mapping

**Comment by ziels** [comment]
Thanks for catching this! I have pushed that change.
