### ISSUE TITLE
expected error rate filtering

### ISSUE THREAD

**Issue by aistBMRG** [ZielsLab/ssUMI#3]
Thanks for developing this workflow! Developing a similar strategy here but without UMIs.

Just a small question. Would it be possible to clarify where in the code filtering based on expected error rates is performed? In the paper, it seems you mentioned that reads were filtered based on an expected error rate of 1%, which removed 90% of reads. Is this performed using vsearch? When using vsearch I found that the quality scores in the ONT reads (using dorado for basecalling) are too high (>41), did you experience such issues? Instead, I am using a custom python script for filtering but just wondering if you experienced such issues?

Also, did you try consensus calling without such strict removal of reads, allowing poorer quality reads?

Thanks!

Dieter

**Comment by ziels** [comment]
Hi Dieter, 

Thanks for this question. In the paper, we applied a 1% EE filter to raw-reads when we *did not* run the ssUMI pipeline. For the ssUMI pipeline, we use a 10% EE filter on raw-reads going into UMI binning. 

The Phred scores of ONT are on a different scale than Illumina. The specific code you requested shows how you can inform VSEARCH of this different Phred scale: 

`$VSEARCH --fastq_filter $TRIM_DIR/{#}_trim.tmp --fastq_ascii 33 --fastq_qmax 93 --fastq_maxee_rate ${MAX_EE} --fastqout $TRIM_DIR/{#}_filt1.tmp` 

The key part there is the `--fastq_ascii 33 --fastq_qmax 93` 

I hope that helps! 

~ Ryan

**Comment by aistBMRG** [comment]
Hi Ryan,

Thanks a lot for taking the time for answering my question -- that fully resolves my issue. Thanks also for clarifying that different EE rate thresholds were applied depending on the analyses .

Best,

Dieter
